### ISSUE TITLE
Add GPX viewer

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-website#5]
On https://opentopomap.org it is possible to view a GPX trace on the map with its profile.
It would be nice and useful for cyclists planning a trip to have also this functionality.
And there are not much website offering this feature so that'd be a good feature to bring people to the site.

**Comment by Phyks** [comment]
BRouter-web will let users do this in next version, see https://github.com/nrenner/brouter-web/pull/240.

I'd be more inclined to having a link to BRouter-web for routing / advanced trip planning rather than developing a full app for cyclosm.

**Comment by Florimondable** [comment]
alright

**Comment by Phyks** [comment]
Since BRouter is definitely the best tool available around for easy routing / GPX viewing etc and it will offer the CyclOSM map background for everyone by default, I'm adding a link to open the current view directly in BRouter-web and relying on its feature: https://github.com/cyclosm/cyclosm-website/commit/c06fe3219210e0175dd4c4e2e9965510f862553e.

Closing this one.
